-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, CAST(A.DAILY_FEE*30 * (1 - P.DISCOUNT_RATE/100) AS SIGNED) AS FEE
FROM (
    SELECT 
    CAR_ID,
    CAR_TYPE,
    DAILY_FEE 
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE < '2022-12-01'
        AND END_DATE >= '2022-11-01'
    )
    AND CAR_TYPE IN ('세단', 'SUV')
    ) AS A
JOIN
(
    SELECT CAR_TYPE, DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE LIKE '30%')
    AS P ON A.CAR_TYPE = P.CAR_TYPE
WHERE CAST(A.DAILY_FEE*30 * (1 - P.DISCOUNT_RATE/100) AS SIGNED) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;