-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT F.FLAVOR, F.TOTAL_ORDER + J.ORDER_SUM AS TOTAL_SUM FROM FIRST_HALF AS F
    JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS ORDER_SUM FROM JULY GROUP BY FLAVOR) AS J
    ON F.FLAVOR = J.FLAVOR
    ORDER BY TOTAL_SUM DESC
) AS A
LIMIT 3;