-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME,I.LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) O
ON I.FISH_TYPE = O.FISH_TYPE
AND I.LENGTH = O.LENGTH
ORDER BY I.ID